"""Source-backed Recamán embedding and Chaffin catalogue visualizer."""

from __future__ import annotations

import json
from pathlib import Path

import gradio as gr
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go


APP_DIR = Path(__file__).resolve().parent
VIEWER_DIR = APP_DIR / "viewer"
TABLE_PATHS = {
    "sequence": VIEWER_DIR / "sequence" / "sequence.parquet",
    "holes": VIEWER_DIR / "holes" / "chaffin_events.parquet",
    "fits": VIEWER_DIR / "fits" / "embedding_checks.parquet",
    "summary": VIEWER_DIR / "summary" / "summary.parquet",
    "obstruction_features": VIEWER_DIR / "obstructions" / "features.parquet",
    "frequency_bands": VIEWER_DIR / "obstructions" / "frequency_bands.parquet",
    "deep_frequency_tests": VIEWER_DIR / "obstructions" / "deep_frequency_tests.parquet",
    "mechanism_trace": VIEWER_DIR / "mechanisms" / "trace.parquet",
    "mechanism_pairs": VIEWER_DIR / "mechanisms" / "pairs.parquet",
    "mechanism_summary": VIEWER_DIR / "mechanisms" / "summary.parquet",
}
MANIFEST_PATH = VIEWER_DIR / "manifest.json"


def load_tables() -> tuple[dict[str, pd.DataFrame], dict[str, object]]:
    missing = [
        str(path)
        for path in [*TABLE_PATHS.values(), MANIFEST_PATH]
        if not path.exists()
    ]
    if missing:
        raise FileNotFoundError(
            "missing generated comparison artifact(s): " + ", ".join(missing)
        )
    tables = {name: pd.read_parquet(path) for name, path in TABLE_PATHS.items()}
    manifest = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    return tables, manifest


TABLES, MANIFEST = load_tables()
SEQUENCE = TABLES["sequence"]
HOLES = TABLES["holes"]
CHECKS = TABLES["fits"]
SUMMARY = TABLES["summary"]
OBSTRUCTION_FEATURES = TABLES["obstruction_features"]
FREQUENCY_BANDS = TABLES["frequency_bands"]
DEEP_FREQUENCY_TESTS = TABLES["deep_frequency_tests"]
MECHANISM_TRACE = TABLES["mechanism_trace"]
MECHANISM_PAIRS = TABLES["mechanism_pairs"]
MECHANISM_SUMMARY = TABLES["mechanism_summary"]


def validation_report() -> str:
    summary = SUMMARY.iloc[0]
    failed = CHECKS.loc[CHECKS["status"] != "PASS"]
    table_status = "PASS" if failed.empty else "FAIL"
    source_hashes = MANIFEST["embedding_sha256"]
    hash_rows = "\n".join(
        f"| `{name}` | `{digest}` |"
        for name, digest in sorted(source_hashes.items())
    )
    return f"""
## Validation status — **{table_status}**

| Check | Result |
|---|---:|
| Independently regenerated Recamán values | **{int(summary.sequence_value_matches):,}/{int(summary.embedding_rows):,} exact** |
| Independently regenerated blocked-step bits | **{int(summary.sequence_blocked_matches):,}/{int(summary.embedding_rows):,} exact** |
| Embedding reconstructions | **{int(summary.embedding_checks_passed)}/{int(summary.embedding_checks_total)} passed** |
| Chaffin events parsed | **{int(summary.chaffin_event_count):,}** |
| Chaffin values represented by those intervals | **{int(summary.chaffin_value_count):,}** |
| Chaffin events in the catalogue feature embedding | **{int(summary.catalogue_feature_events_covered):,}/{int(summary.chaffin_event_count):,}** |

### Source hashes

| Artifact | SHA-256 |
|---|---|
{hash_rows}

The tables are generated by `scripts/build_comparison_tables.py`; CI reruns it
with `--check` and fails on any source hash, value, bit, embedding, catalogue,
or generated-table drift.
"""


def overview() -> str:
    row = SUMMARY.iloc[0]
    return f"""
# Recamán Independent Check Visualizer

This viewer compares the published embedding bundle with an independently
regenerated Recamán prefix and places the Chaffin catalogue beside its actual
finite horizon.

| Evidence | Coverage |
|---|---:|
| Embedded Recamán steps | **0–{int(row.embedding_steps):,}** |
| Embedded value range | **{int(row.embedding_value_min):,}–{int(row.embedding_value_max):,}** |
| First Chaffin catalogue value | **{int(row.chaffin_min):,}** |
| Last Chaffin catalogue value | **{int(row.chaffin_max):,}** |
| Chaffin events inside embedding value span | **{int(row.chaffin_events_within_embedding_span):,}** |
| Early holes traced through the exact recurrence | **{int(row.mechanism_holes_traced):,}** |
| Mechanism-trace horizon | **{int(row.mechanism_horizon_steps):,} steps** |

### Honest conclusion

The embeddings reconstruct the finite Recamán prefix exactly. The Chaffin
catalogue begins at **{int(row.chaffin_min):,}**, far above the embedding's
maximum observed value of **{int(row.embedding_value_max):,}**. Therefore this
bundle validates the embeddings, but its `N={int(row.embedding_steps):,}`
horizon cannot validate or falsify any Chaffin hole. No inferred-hole rows or
synthetic predictions are used.
"""


def mechanism_view() -> tuple[go.Figure, pd.DataFrame, pd.DataFrame, str]:
    holes = MECHANISM_TRACE.loc[
        MECHANISM_TRACE["group"] == "catalogue_hole"
    ].copy()
    counts = (
        holes["mechanism"]
        .value_counts()
        .rename_axis("mechanism")
        .reset_index(name="holes")
    )
    counts["mechanism"] = counts["mechanism"].map(
        {
            "no_observed_proposal": "Never proposed through 10M steps",
            "bypassed_addition_only": "Addition candidate bypassed",
        }
    )
    figure = px.bar(
        counts,
        x="mechanism",
        y="holes",
        color="mechanism",
        color_discrete_map={
            "Never proposed through 10M steps": "#475569",
            "Addition candidate bypassed": "#b7791f",
        },
        text="holes",
        title="Exact missed-opportunity mechanism for 103 early catalogue holes",
        labels={"mechanism": "Observed transition history", "holes": "Catalogue values"},
    )
    figure.update_layout(showlegend=False, xaxis_title=None)

    first = holes.loc[holes["value"] == 852_655].iloc[0]
    upper_controls = MECHANISM_PAIRS.loc[MECHANISM_PAIRS["side"] == "upper"]
    explanation = f"""
## Mechanism-first result

The recurrence was executed exactly for **10,000,000 steps**. For every one of
the **103 catalogue values at or below 10,000,000**, the analysis recorded both
possible landing proposals before the branch decision.

- **{int((holes['mechanism'] == 'no_observed_proposal').sum())} holes** were
  never proposed on either branch during the run.
- **{int((holes['mechanism'] == 'bypassed_addition_only').sum())} holes**
  appeared as the addition candidate exactly when a legal subtraction took
  precedence.
- No catalogue hole was a subtraction candidate: if a positive unseen value
  had appeared there, the rule would have landed on it immediately.
- The first known hole, **852,655**, had
  **{int(first.up_proposals)} observed proposals** through the horizon.
- All **{int(upper_controls['control_visited'].sum())}** upper adjacent controls
  were already visited; this is a local contrast, not a randomized causal
  estimate.

### Boundary of the claim

For a target `m`, addition opportunities are complete after step `m`; all 103
targets meet that condition here. Subtraction opportunities can occur later,
so their absence is right-censored at 10,000,000 steps. This trace explains the
finite missed opportunities. It does **not** prove permanent holes.
"""
    columns = [
        "value",
        "mechanism",
        "up_proposals",
        "up_bypassed",
        "down_proposals",
        "first_bypass_step",
    ]
    return figure, holes[columns], MECHANISM_PAIRS, explanation


def obstruction_feature_view() -> tuple[go.Figure, pd.DataFrame]:
    figure = px.scatter_3d(
        OBSTRUCTION_FEATURES,
        x="log10_start",
        y="log10_gap_plus_one",
        z="log10_length",
        color="log10_length",
        color_continuous_scale="Cividis",
        hover_data=["event_id", "start", "end", "length", "gap_from_previous"],
        title="Interpretable feature embedding of all catalogued obstruction events",
        labels={
            "log10_start": "log10(event start)",
            "log10_gap_plus_one": "log10(previous gap + 1)",
            "log10_length": "log10(run length)",
        },
    )
    figure.update_traces(marker={"size": 3, "opacity": 0.72})
    return figure, OBSTRUCTION_FEATURES


def frequency_view() -> tuple[go.Figure, pd.DataFrame, pd.DataFrame, str]:
    plot_data = FREQUENCY_BANDS.melt(
        id_vars="band",
        value_vars=["events_per_million", "missing_values_per_million"],
        var_name="measure",
        value_name="rate_per_million",
    )
    plot_data["measure"] = plot_data["measure"].map(
        {
            "events_per_million": "Event starts per million candidates",
            "missing_values_per_million": "Missing values per million candidates",
        }
    )
    figure = px.bar(
        plot_data,
        x="band",
        y="rate_per_million",
        color="measure",
        barmode="group",
        log_y=True,
        color_discrete_map={
            "Event starts per million candidates": "#2563a6",
            "Missing values per million candidates": "#b7791f",
        },
        title="Observed catalogue frequency by value band",
        labels={"band": "Candidate-value band", "rate_per_million": "Rate per million (log scale)"},
    )
    figure.update_layout(legend_title_text=None)

    last = FREQUENCY_BANDS.iloc[-1]
    explanation = f"""
### What changes after 852,655?

Both observations below are true because they use different denominators:

- per fixed million candidate integers, event starts become less dense;
- per equal multiplicative (`log10`) value interval, events become more
  frequent—including events at every predeclared run-depth threshold.

The 24-bin permutation test supports the multiplicative-scale increase after
Holm correction at run lengths ≥1, ≥2, ≥10, ≥100, and ≥1,000. Later events also
increasingly include contiguous runs instead of isolated values.

In the final displayed band, **{float(last.extension_share_of_missing):.1%}** of
catalogued missing values are run-extension values beyond the event starts.
That supports a precise structural hypothesis: investigate why local Recamán
state creates *clusters/runs* of missed values, rather than claiming that the
independent event-arrival rate simply increases.

These are descriptive catalogue statistics after `10^612` computed terms. They
do not establish causation or prove that a catalogued hole is absent forever.
"""
    return figure, FREQUENCY_BANDS, DEEP_FREQUENCY_TESTS, explanation


def sequence_view(n_end: int) -> tuple[go.Figure, pd.DataFrame]:
    end = max(0, min(int(n_end), int(SEQUENCE["n"].max())))
    visible = SEQUENCE.loc[SEQUENCE["n"] <= end]
    figure = go.Figure()
    figure.add_trace(
        go.Scattergl(
            x=visible["n"],
            y=visible["a_n_reference"],
            mode="lines",
            name="Independent recurrence",
        )
    )
    figure.add_trace(
        go.Scattergl(
            x=visible["n"],
            y=visible["a_n_embedding"],
            mode="markers",
            marker={"size": 3, "opacity": 0.55},
            name="Published NPZ",
        )
    )
    mismatches = visible.loc[
        ~(visible["value_exact"] & visible["blocked_exact"])
    ]
    if not mismatches.empty:
        figure.add_trace(
            go.Scattergl(
                x=mismatches["n"],
                y=mismatches["a_n_embedding"],
                mode="markers",
                marker={"color": "red", "size": 9},
                name="Mismatch",
            )
        )
    figure.update_layout(
        title=f"Published embedding vs independent recurrence through n={end:,}",
        xaxis_title="Step n",
        yaxis_title="a(n)",
        hovermode="closest",
    )
    return figure, mismatches


def embedding_checks_view() -> tuple[go.Figure, pd.DataFrame]:
    figure = px.bar(
        CHECKS,
        x="check",
        y="rows",
        color="status",
        color_discrete_map={"PASS": "#159957", "FAIL": "#d73a49"},
        hover_data=["exact_rows", "max_abs_error", "source_file", "sha256"],
        title="Exact rows checked for every published embedding",
    )
    figure.update_layout(xaxis_title=None, yaxis_title="Rows checked")
    return figure, CHECKS


def chaffin_view(minimum_length: int) -> tuple[go.Figure, pd.DataFrame, str]:
    minimum = max(1, int(minimum_length))
    visible = HOLES.loc[HOLES["length"] >= minimum].copy()
    figure = px.scatter(
        visible,
        x="start",
        y="length",
        color="coverage_status",
        log_x=True,
        log_y=True,
        hover_data=["event_id", "end", "within_embedding_value_span"],
        title=f"Chaffin catalogue events with length ≥ {minimum:,}",
    )
    figure.update_layout(
        xaxis_title="Catalogue event start (log scale)",
        yaxis_title="Event length (log scale)",
    )
    row = SUMMARY.iloc[0]
    boundary = f"""
### Horizon boundary

The embedding reaches value **{int(row.embedding_value_max):,}**. The first
Chaffin event starts at **{int(row.chaffin_min):,}**. Consequently,
**{int(row.chaffin_events_within_embedding_span):,} of {int(row.chaffin_event_count):,}**
catalogue events overlap the embedding's observed value span. `OUTSIDE_EMBEDDING_SPAN`
means *not testable by this finite embedding*, not confirmed or rejected.
"""
    return figure, visible.head(5_000), boundary


with gr.Blocks(title="Recamán Independent Check Visualizer") as demo:
    gr.Markdown(overview())

    with gr.Tab("Hole mechanisms"):
        mechanism_explanation = gr.Markdown()
        mechanism_plot = gr.Plot()
        mechanism_table = gr.Dataframe(
            interactive=False, label="Per-hole exact transition trace"
        )
        mechanism_pair_table = gr.Dataframe(
            interactive=False, label="Adjacent-value controls"
        )

    with gr.Tab("Sequence identity"):
        sequence_end = gr.Slider(
            minimum=100,
            maximum=int(SEQUENCE["n"].max()),
            value=int(SEQUENCE["n"].max()),
            step=100,
            label="Display through step n",
        )
        sequence_plot = gr.Plot()
        mismatch_table = gr.Dataframe(
            headers=list(SEQUENCE.columns),
            label="Mismatches (empty means exact)",
            interactive=False,
        )
        sequence_end.change(
            sequence_view,
            inputs=sequence_end,
            outputs=[sequence_plot, mismatch_table],
        )

    with gr.Tab("Embedding checks"):
        check_plot = gr.Plot()
        check_table = gr.Dataframe(
            interactive=False,
            label="Exact reconstruction checks",
        )
        gr.Markdown(validation_report())

    with gr.Tab("Chaffin coverage"):
        minimum_length = gr.Slider(
            minimum=1,
            maximum=max(1, int(HOLES["length"].max())),
            value=1,
            step=1,
            label="Minimum catalogue event length",
        )
        hole_plot = gr.Plot()
        hole_table = gr.Dataframe(interactive=False, label="Catalogue events")
        boundary_report = gr.Markdown()
        minimum_length.change(
            chaffin_view,
            inputs=minimum_length,
            outputs=[hole_plot, hole_table, boundary_report],
        )

    with gr.Tab("Raw evidence"):
        gr.Markdown(
            "All downloadable files below are the exact tables used by the charts."
        )
        for label, path in TABLE_PATHS.items():
            gr.DownloadButton(
                label=f"Download {label} Parquet",
                value=str(path),
            )
        gr.JSON(value=MANIFEST, label="Provenance manifest")

    demo.load(
        sequence_view,
        inputs=sequence_end,
        outputs=[sequence_plot, mismatch_table],
    )
    demo.load(embedding_checks_view, outputs=[check_plot, check_table])
    demo.load(
        chaffin_view,
        inputs=minimum_length,
        outputs=[hole_plot, hole_table, boundary_report],
    )
    demo.load(
        mechanism_view,
        outputs=[
            mechanism_plot,
            mechanism_table,
            mechanism_pair_table,
            mechanism_explanation,
        ],
    )


if __name__ == "__main__":
    demo.launch()
